First commits
cisagov/egress-assess-packer pull request #11
Opened 2023-01-19 17:56 UTC by m1j09830

# Merge first-commits branch with develop branch#

## 🗣 Description ##

In this pull request the Egress-Assess first commit branch will be merged with the develop. The first-commit branch has been fully tested for functionality with the COOL Staging environment and is reach to be moved into production

## 💭 Motivation and context ##

This change is required to allow egress testing of networks during engagements
A specific instance needed to be created in order to isolate the instance from other COOL resources

## 🧪 Testing ##

Changes were initially made to the first-commits branch and tested in the COOL Staging environment
An AMI was built based on the first-commit branch and deployed to the staging environment
Tests were conducted to ensure proper connection and exchange of data between the Egress-Assess server and client 

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Add a tag or create a release.

2023-01-20 16:29 UTC, jsf9k requested changes
Looks good!  I'm only requesting a few minor changes.

2023-01-20 16:29 UTC, jsf9k commented on src/packer.pkr.hcl
> +source "amazon-ebs" "egress-assess" {
We prefer snake case for HCL:
```suggestion
source "amazon-ebs" "egress_assess" {
```

2023-01-20 16:29 UTC, jsf9k commented on src/packer.pkr.hcl
> +  sources = ["source.amazon-ebs.egress-assess"]
To maintain consistency with my previous suggestion in this file:
```suggestion
  sources = ["source.amazon-ebs.egress_assess"]
```

2023-01-20 16:29 UTC, jsf9k commented on README.md
> +[Egress-Assess](https://github.com/FortyNorthSecurity/Egress-Assess) installed.
You're installing from [tarrell13/Egress-Assess](https://github.com/tarrell13/Egress-Assess), and according to #13 you intend to continue doing so, so this link should be updated:
```suggestion
[Egress-Assess](https://github.com/tarrell13/Egress-Assess) installed.
```

2023-01-20 17:00 UTC, jsf9k approved these changes
:+1:

2023-01-20 17:01 UTC, dav3r approved these changes
Great work @m1j09830 🚀

2023-01-20 17:01 UTC, jsf9k commented
@m1j09830 - don't forget to finalize the version before merging.

2023-01-20 17:02 UTC, dav3r commented
@mcdonnnj - Please review this PR even though it already has 2 dev reviews, since I helped @m1j09830 significantly and therefore my review is fairly biased.

2023-02-02 16:38 UTC, mcdonnnj requested changes

2023-02-02 16:38 UTC, mcdonnnj commented on src/cloud_init.yml
> +        - cloud-final
We prefer to sort things like this. If the current order is required then it should be documented. I see this appears to be an inherited thing from cribbing other Packer projects so as long so we should update those projects based on the resolution of this conversation.

```suggestion
        - cloud-config
        - cloud-final
        - cloud-init
        - cloud-init-local
```

2023-02-02 16:38 UTC, mcdonnnj commented on src/egress_assess.yml
> +        tarball/Forked"
This needs to be updated in line with the resolution of https://github.com/cisagov/kali-packer/pull/141#discussion_r1089255813.

2023-02-02 16:38 UTC, mcdonnnj commented on README.md
> +[Egress-Assess](https://github.com/tarrell13/Egress-Assess) installed.
This also needs to be updated with the resolution of https://github.com/cisagov/kali-packer/pull/141#discussion_r1089255813.

2023-02-02 16:46 UTC, dav3r commented on src/cloud_init.yml
> +        - cloud-final
Yes, this list of items should be sorted here and elsewhere.

2023-02-06 16:20 UTC, m1j09830 commented on src/egress_assess.yml
> +        tarball/Forked"
Made changes in `egress_assess.yml` to reflect updated repository. Please see f877fb21591423a51ef16ce07bb25397fcd1d0d3. Updated issue #13 to properly reflect the changes and close out the issue.

2023-02-06 16:20 UTC, m1j09830 commented on README.md
> +[Egress-Assess](https://github.com/tarrell13/Egress-Assess) installed.
Made the changes to the README per the suggestion above. Please see 14c06dc77fda40c87e7bfde16ff90cf7531b6efe

2023-02-07 20:20 UTC, mcdonnnj requested changes
Thanks for resolving my previous feedback. I have two more small items from re-reviewing.

2023-02-07 20:20 UTC, mcdonnnj commented on terraform-build-user/main.tf
> +    "/ssh/public_keys/*",
I don't believe this configuration needs access to these SSM parameters.
```suggestion
```

2023-02-07 20:20 UTC, mcdonnnj commented on src/egress_assess.yml
> +  name: Install Egress-Assess tool
I'm fine with the playbook name remaining the same but I think this descriptor should reflect the tool being installed.

```suggestion
  name: Install Auto-Egress-Assess tool
```

2023-02-07 20:32 UTC, dav3r commented on terraform-build-user/main.tf
> +    "/ssh/public_keys/*",
Ah you are right now that we have stopped including [cisagov/ansible-role-dev-ssh-access](https://github.com/cisagov/ansible-role-dev-ssh-access) in our AMIs.  We should probably remove these [from skeleton-packer also](https://github.com/cisagov/skeleton-packer/blob/078fd4c8cbaac9597a3e599f6b9f487b54a4b5b2/terraform-build-user/main.tf#L12).

2023-02-07 20:44 UTC, mcdonnnj commented on terraform-build-user/main.tf
> +    "/ssh/public_keys/*",
@dav3r Yes I have this draft PR toward that work: https://github.com/cisagov/ami-build-iam-user-tf-module/pull/53

2023-02-08 15:25 UTC, mcdonnnj approved these changes
LGTM ✔

2023-02-08 16:55 UTC, merged